//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashB_KPITargetBySalesRoute_Period
    {
        public System.Guid Id { get; set; }
        public string Period { get; set; }
        public string DistributorCode { get; set; }
        public string SalesRouteCode { get; set; }
        public string KPICode { get; set; }
        public Nullable<double> KPITarget { get; set; }
        public string CompanyCode { get; set; }
        public string SalesOrgCode { get; set; }
        public string Source { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
