//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashB_SalesForce
    {
        public string CompanyCode { get; set; }
        public string SalesOrgCode { get; set; }
        public string SalesForceCode { get; set; }
        public string SalesForceName { get; set; }
        public int SalesForceLevel { get; set; }
        public string ParentCode { get; set; }
        public string EmployeeCode { get; set; }
        public int Ordinal { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string ExcutedBy { get; set; }
        public string ExecutedDateTime { get; set; }
    }
}
