//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashB_SellInTarget_Period
    {
        public System.Guid Id { get; set; }
        public string Period { get; set; }
        public string SalesForceCode { get; set; }
        public int SalesForceLevel { get; set; }
        public string DistributorCode { get; set; }
        public string BrandCode { get; set; }
        public Nullable<double> SellinTarget { get; set; }
        public string CompanyCode { get; set; }
        public string SalesOrgCode { get; set; }
        public string Source { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public bool Deleted { get; set; }
    }
}
