//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardMT_SalesByWholeSaler_Period
    {
        public string Period { get; set; }
        public string Region { get; set; }
        public string WholeSalerID { get; set; }
        public Nullable<double> SalesTarget { get; set; }
        public Nullable<double> SalesActual { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    }
}
