//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashB_SalesRoute
    {
        public string CompanyCode { get; set; }
        public string SalesOrgCode { get; set; }
        public string CustomerCode { get; set; }
        public string SalesRouteCode { get; set; }
        public string SalesRouteName { get; set; }
        public string SalesPersonCode { get; set; }
        public string SalesTeamCode { get; set; }
        public string SalesForceCode { get; set; }
        public string SalesForceL1 { get; set; }
        public string SalesForceL2 { get; set; }
        public string SalesForceL3 { get; set; }
        public string SalesForceL4 { get; set; }
        public string SalesForceL5 { get; set; }
        public string SalesForceL6 { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string ExcutedBy { get; set; }
        public string ExecutedDateTime { get; set; }
    }
}
