//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMSSERVER_BINHHTEntities : DbContext
    {
        public DMSSERVER_BINHHTEntities()
            : base("name=DMSSERVER_BINHHTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DashB_KPITargetBySalesRoute_Period> DashB_KPITargetBySalesRoute_Period { get; set; }
        public virtual DbSet<DashB_SalesForce> DashB_SalesForce { get; set; }
        public virtual DbSet<DashB_SalesRoute> DashB_SalesRoute { get; set; }
        public virtual DbSet<DashB_SalesTarget_Period> DashB_SalesTarget_Period { get; set; }
        public virtual DbSet<DashB_SellInTarget_Period> DashB_SellInTarget_Period { get; set; }
        public virtual DbSet<DashBoardMT_ProductBySalesRep_Period> DashBoardMT_ProductBySalesRep_Period { get; set; }
        public virtual DbSet<DashBoardMT_SalesBySalesRep_Period> DashBoardMT_SalesBySalesRep_Period { get; set; }
        public virtual DbSet<DashBoardMT_SalesByWholeSaler_Period> DashBoardMT_SalesByWholeSaler_Period { get; set; }
    }
}
