//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EMSalesForces = new HashSet<EMSalesForce>();
        }
    
        public System.Guid ID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string ReferenceEmployeeCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Gender { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IdentityCard { get; set; }
        public string IdentityCardPlace { get; set; }
        public Nullable<System.DateTime> IdentityCardDate { get; set; }
        public string IdentityCardAddress { get; set; }
        public string PaymentType { get; set; }
        public string TaxType { get; set; }
        public string TaxCode { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public bool SalesPerson { get; set; }
        public bool DeliveryPerson { get; set; }
        public bool CashCollector { get; set; }
        public string PostalCode { get; set; }
        public string Ward { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string RegionCode { get; set; }
        public string RegionL1 { get; set; }
        public string RegionL2 { get; set; }
        public string RegionL3 { get; set; }
        public string RegionL4 { get; set; }
        public string RegionL5 { get; set; }
        public string RegionL6 { get; set; }
        public string JobTitle { get; set; }
        public string ContractCode { get; set; }
        public Nullable<System.DateTime> ContractExpiredDate { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public string HealthAssuranceNumber { get; set; }
        public string EducationDegree { get; set; }
        public string College { get; set; }
        public string HighSchool { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public string Leader { get; set; }
        public string Department { get; set; }
        public string WarehouseCode { get; set; }
        public string SalesGroup { get; set; }
        public string ContractType { get; set; }
        public string EmployeeGroup { get; set; }
        public string EmployeeType { get; set; }
        public string Remark { get; set; }
        public string CompanyCode { get; set; }
        public string SalesOrgCode { get; set; }
        public string Source { get; set; }
        public int CreatedBy { get; set; }
        public int LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public int RowVersion { get; set; }
        public bool Deleted { get; set; }
        public long RowNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMSalesForce> EMSalesForces { get; set; }
    }
}
