//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_SellIn
    {
        public string Day { get; set; }
        public string Region { get; set; }
        public string KeyAccount { get; set; }
        public string Channel { get; set; }
        public string Archive { get; set; }
        public string LastMonth { get; set; }
        public string TargetMonth { get; set; }
        public string TargetDate { get; set; }
        public string Actual { get; set; }
        public string Growth { get; set; }
        public string GrowthLastMonth { get; set; }
        public string PercentTarget { get; set; }
        public string TargetWeek { get; set; }
        public string ActualWeek { get; set; }
        public string PercentWeek { get; set; }
        public string CurrentDate { get; set; }
        public int ID { get; set; }
        public string LastUpdated { get; set; }
        public string Tab { get; set; }
        public string CompanyCode { get; set; }
        public string SalesOrg { get; set; }
    }
}
