//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_SellOut
    {
        public string SalesOrg { get; set; }
        public string CustomerCode { get; set; }
        public string SalesRouteCode { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Store { get; set; }
        public string Target { get; set; }
        public string Perform { get; set; }
        public string Rate { get; set; }
        public Nullable<int> LineID { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<int> SalesForceLevel { get; set; }
        public string ParentCode { get; set; }
    }
}
