//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesForce
    {
        public System.Guid ID { get; set; }
        public string SalesForceCode { get; set; }
        public int SalesForceLevel { get; set; }
        public string SalesForceName { get; set; }
        public string SalesForceName2 { get; set; }
        public string SalesForceName3 { get; set; }
        public int Ordinal { get; set; }
        public string ParentCode { get; set; }
        public string Status { get; set; }
        public string CompanyCode { get; set; }
        public string SalesOrgCode { get; set; }
        public string Source { get; set; }
        public int CreatedBy { get; set; }
        public int LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public int RowVersion { get; set; }
        public bool Deleted { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public long RowNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
