//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOut
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Chain { get; set; }
        public string Target { get; set; }
        public string Perform { get; set; }
        public string Rate { get; set; }
    }
}
